% /************************************************************************
%  File name   :	Figuras.m
%  Originator  : 	Alejandro Espinoza
%  Description : 	Figuras, resultados de simulación
%
% -------------------------------------------------------------------------
% =======================================================================*/
clc
%grafica de corriente de carga
figure('Units','inches','Position',[3 3 6 2.5],'PaperPositionMode','auto');
plot(IL_abc.time,IL_abc.data(:,1),'r','LineWidth',1)
hold on
plot(IL_abc.time,IL_abc.data(:,2),'b','LineWidth',1)
hold on
plot(IL_abc.time,IL_abc.data(:,3),'color',[0 0.5 0],'LineWidth',1)
plot(Is_abc.time,Is_abc.data(:,1),'r','LineWidth',1)
hold on
plot(Is_abc.time,Is_abc.data(:,2),'b','LineWidth',1)
hold on
plot(Is_abc.time,Is_abc.data(:,3),'color',[0 0.5 0],'LineWidth',1)
axis( [0 0.15 -4.5 4.5])
grid on
set(gca,...
'Units','normalized',...
'YTick',[-4.5:1.5:4.5],...
'XTick',[0:0.03:0.15],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'Corriente Carga [A]'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Tiempo(s)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$i_{L}^a$','$i_{L}^b$','$i_{L}^c$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','bestoutside')
print -dpdf i_L_abc.pdf

%grafica de corriente de red
figure('Units','inches','Position',[03 03 6 2.5],'PaperPositionMode','auto');
plot(Is_abc.time,Is_abc.data(:,1),'r','LineWidth',1)
hold on
plot(Is_abc.time,Is_abc.data(:,2),'b','LineWidth',1)
hold on
plot(Is_abc.time,Is_abc.data(:,3),'color',[0 0.5 0],'LineWidth',1)
axis( [0 0.15 -4.5 4.5])
grid on
set(gca,...
'Units','normalized',...
'YTick',[-4.5:1.5:4.5],...
'XTick',[0:0.03:0.15],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'Corriente Red [A]'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Tiempo(s)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$i_{s}^a$','$i_{s}^b$','$i_{s}^c$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','bestoutside')
print -dpdf i_s_abc.pdf

%corriente del APF
figure('Units','inches','Position',[03 03 6 2.5],'PaperPositionMode','auto');
plot(IC_abc.time,IC_abc.data(:,1),'r','LineWidth',1)
hold on
plot(IC_abc.time,IC_abc.data(:,2),'b','LineWidth',1)
hold on
plot(IC_abc.time,IC_abc.data(:,3),'color',[0 0.5 0],'LineWidth',1)
axis( [0 0.15 -3 3])
grid on
set(gca,...
'Units','normalized',...
'YTick',[-3:1:3],...
'XTick',[0:0.03:0.15],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'Corriente APF [A]'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Tiempo(s)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$i_{c}^a$','$i_{c}^b$','$i_{c}^c$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','bestoutside')
print -dpdf i_c_abc.pdf

%grafica del referencias corriente
figure('Units','inches','Position',[03 03 6 2.5],'PaperPositionMode','auto');
plot(IR_IC_abc.time,IR_IC_abc.data(:,1),'r','LineWidth',1.5)
hold on
plot(IR_IC_abc.time,IR_IC_abc.data(:,4),'b','LineWidth',0.75)
axis( [0 0.15 -3 3])
grid on
set(gca,...
'Units','normalized',...
'YTick',[-3:1.5:3],...
'XTick',[0:0.03:0.15],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'Referencia [A]'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Tiempo(s)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$i_{Ref}^a$','$i_{c}^a$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','bestoutside')
print -dpdf i_ref.pdf

%grafica reactiva
figure('Units','inches','Position',[03 03 6 2.5],'PaperPositionMode','auto');
plot(Qs_k.time,Qs_k.data(:,1),'r','LineWidth',0.75)
hold on
plot(Qc_k.time,Qc_k.data(:,1),'b','LineWidth',0.75)
hold on
plot(QL_k.time,QL_k.data(:,1),'color',[0 0.5 0],'LineWidth',1.5)
axis( [0 0.15 -100 900])
grid on
set(gca,...
'Units','normalized',...
'YTick',[-100:100:900],...
'XTick',[0:0.03:0.15],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'Potencia Reactiva [VAR]'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Tiempo(s)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$Q_S$','$Q_C$','$Q_L$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','bestoutside')
print -dpdf Reactiva.pdf

%grafica activa
figure('Units','inches','Position',[03 03 6 2.5],'PaperPositionMode','auto');
plot(Ps_k.time,Ps_k.data(:,1),'r','LineWidth',0.75)
hold on
plot(Pc_k.time,Pc_k.data(:,1),'b','LineWidth',0.75)
hold on
plot(PL_k.time,PL_k.data(:,1),'color',[0 0.5 0],'LineWidth',1.5)
axis( [0 0.15 -400 1000])
grid on
set(gca,...
'Units','normalized',...
'YTick',[-400:400:1000],...
'XTick',[0:0.02:0.15],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'Potencia Activa [W]'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Tiempo(s)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$P_S$','$P_C$','$P_L$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','bestoutside')
print -dpdf activa.pdf

%grafica Vs_abc
figure('Units','inches','Position',[03 03 6 2.5],'PaperPositionMode','auto');
plot(Vs_Vf_abc.time,Vs_Vf_abc.data(:,1),'r','LineWidth',1.5)
hold on
plot(Vs_Vf_abc.time,Vs_Vf_abc.data(:,4),'b','LineWidth',0.75)
axis( [0 0.15 -220 220])
grid on
set(gca,...
'Units','normalized',...
'YTick',[-200:100:200],...
'XTick',[0:0.03:0.15],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'Voltaje APF [V]'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Tiempo(s)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$v_s^a$','$v_c^a$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','southoutside')
print -dpdf Vc_abc.pdf

%grafica capacitores
figure('Units','inches','Position',[03 03 6 2.5],'PaperPositionMode','auto');
plot(Vcaps.time,Vcaps.data(:,1),'k','LineWidth',2)
hold on
plot(Vcaps.time,Vcaps.data(:,2),'b','LineWidth',1)
hold on
plot(Vcaps.time,Vcaps.data(:,3),'color',[0 0.5 0],'LineWidth',1)
hold on
plot(Vcaps.time,Vcaps.data(:,4),'y','LineWidth',1)
hold on
plot(Vcaps.time,Vcaps.data(:,5),'m','LineWidth',1)
hold on
plot(Vcaps.time,Vcaps.data(:,6),'c','LineWidth',1)
hold on
plot(Vcaps.time,Vcaps.data(:,7),'r','LineWidth',1)
hold on
plot(Vcaps.time,Vcaps.data(:,8),'g','LineWidth',1)
hold on
plot(Vcaps.time,Vcaps.data(:,9),'color',[0.8500 0.3250 0.0980],'LineWidth',1)
hold on
plot(Vcaps.time,Vcaps.data(:,10),'color',[0.4940 0.1840 0.5560],'LineWidth',1)
axis([0 0.15 60 65])
grid on
set(gca,...
'Units','normalized',...
'YTick',[60:1:65],...
'XTick',[0:0.03:0.15],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'Voltaje Capacitores [V]'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Tiempo(s)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$V_{ref}$','$V_{dc1}^a$','$V_{dc2}^a$','$V_{dc3}^a$','$V_{dc1}^b$','$V_{dc2}^b$','$V_{dc3}^b$','$V_{dca}^c$','$V_{dc2}^c$','$V_{dc3}^c$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','southoutside')
print -dpdf Vcaps.pdf

%Factor de potencia de desplazamiento y FP
figure('Units','inches','Position',[03 03 6 2.5],'PaperPositionMode','auto');
plot(FP.time,FP.data(:,1),'r','LineWidth',1)
hold on
plot(FP.time,FP.data(:,2),'b','LineWidth',1)
hold on
plot(FPD.time,FPD.data(:,1),'color',[0 0.5 0],'LineWidth',1)
hold on
plot(FPD.time,FPD.data(:,2),'m','LineWidth',1)
axis( [0 0.15 0.9 1.05])
grid on
set(gca,...
'Units','normalized',...
'YTick',[0.9:0.025:1.05],...
'XTick',[0:0.03:0.15],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'FP y FPD'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Tiempo(s)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$FP_s^a$','$FP_L^a$','$FPD_s^a$','$FPD_L^a$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','southoutside')
print -dpdf FP_FPD.pdf

%Factor de potencia de desplazamiento y FP
figure('Units','inches','Position',[03 03 6 2.5],'PaperPositionMode','auto');
plot(THD.time,THD.data(:,1),'r','LineWidth',1)
hold on
plot(THD.time,THD.data(:,2),'b','LineWidth',1)
hold on
axis( [0 0.15 0 35])
grid on
set(gca,...
'Units','normalized',...
'YTick',[0:5:35],...
'XTick',[0:0.03:0.15],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'THD $[\%]$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Tiempo(s)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$THD_s^a$','$THD_L^a$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','southoutside')
print -dpdf THD.pdf
