clc
clear all
close all
fm_fd = 1000;
fn = fm_fd/2;
[num den] = butter(2,25/fn,'low');
H = tf(num,den,1/fm_fd);
bode(H)
[mag,phase,wout] = bode(Hd)
dbmag = 20*log10(mag)
figure('Units','inches','Position',[3 3 6 2],'PaperPositionMode','auto');
plot(wout(:,1),dbmag(:,1),'r','LineWidth',1)
grid on
set(gca,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
ylabel({'Magnitud [dB]'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('Frecuencia(Hz)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
legend({'$Magnitud(dB)$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times',...
'Orientation','horizontal',...
'Location','bestoutside')
print -dpdf bode.pdf